function init(self)
	gui.set_render_order(14)
	self.node = gui.get_node("c")
	msg.post("#", "acquire_input_focus")
	self.handle = nil
end

function on_input(self, action_id, action)
	local pos = vmath.vector3(action.x, action.y, 0)
	gui.set_position(self.node, pos)
	if action.pressed and action_id == hash("touch") then
		if self.handle then
			timer.cancel(self.handle)
		end
		gui.set_enabled(self.node, false)
		self.handle = timer.delay(2, false, function()
			gui.set_enabled(self.node, true)
		end)
	end
end